site_name: OLDL
site_author: Eray Erdin

theme:
  name: material
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/erayerdin
  disqus: erayerdin

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes

nav:
  - Home: index.md
  - For Everyday Users:
      - An Introduction: everydayusers.md
  - For Implementors:
      - General Structure: structure.md
      - Body:
          - Key-Value Pairs: keyvalue.md
          - Data Types: datatypes.md
      - Content: content.md
  - For Developers:
      - Implementations: implementations.md
