site_name: OLDL
site_author: Eray Erdin

theme:
  name: material
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/erayerdin
  disqus: erayerdin

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - For Everyday Users:
      - An Introduction: everydayusers.md
  - For Implementors and Developers:
      - General Structure: structure.md
      - Pairs: pairs.md
      - Texts: texts.md
  - For Developers:
      - Implementations: implementations.md
